In [1]:
#0-d ARRAY
import numpy as np
arr=np.array(42)
print(arr)

42


In [7]:
#1-d ARRAY
import numpy as np
arr=np.array([2,6,4,9,10])
print(arr)

[ 2  6  4  9 10]


In [3]:
#2-d ARRAY
import numpy as np
arr=np.array([[10,20,30],[90,80,70]])
print(arr)

[[10 20 30]
 [90 80 70]]


In [6]:
#3-d ARRAY
import numpy as np
arr=np.array([[[22,33,44],[12,13,14]],[[77,66,88],[23,98,67,]]])
print(arr)

[[[22 33 44]
  [12 13 14]]

 [[77 66 88]
  [23 98 67]]]


In [8]:
#finding dimensions of the arrays
import numpy as np
a=np.array(42)
b=np.array([2,6,4,9,10])
c=np.array([[10,20,30],[90,80,70]])
d=np.array([[[22,33,44],[12,13,14]],[[77,66,88],[23,98,67,]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [9]:
#printing sum of elements inside the array
import numpy as np
arr=np.array([1,2,9,8,7])
print(arr[2]+arr[4])

16


In [10]:
#printing the elemennt at the entered index
import numpy as np
arr=np.array([1,2,9,8,7])
print(arr[2])

9


In [11]:
#accesing elements of 2-d array
import numpy as np
arr=np.array([[10,20,30],[90,80,70]])
print("3rd element of 2nd row:",arr[1,2])

3rd element of 2nd row: 70


In [12]:
#slicing
import numpy as np
arr=np.array([2,6,4,9])
print(arr[1:4])

[6 4 9]


In [13]:
#slicing
import numpy as np
arr=np.array([2,6,4,77,23,90])
print(arr[:5])

[ 2  6  4 77 23]


In [14]:
#slicing
import numpy as np
arr=np.array([2,6,4,77,23,90])
print(arr[:])

[ 2  6  4 77 23 90]


In [15]:
#negative slicing
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr[-4:-1])

[3 4 5]


In [16]:
#step slicing
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr[1:3:2])

[2]


In [17]:
#return every other
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr[::3])

[1 4]


In [18]:
#slicing 2-d array
import numpy as np
arr=np.array([[10,20,30],[90,80,70]])
print(arr[1,1:3])

[80 70]
